//
//  DataManager.swift
//  report
//
//  Created by osa on 01.06.2021.
//

class DataManager {
    static let shared = DataManager()
    
    let operationImages = ["dollarsign.circle", "globe", "airplane", "calendar", "rublesign.circle", "doc", "creditcard", "text.justify"]
    
    let operationNames = ["Ввести сумму", "Выбрать валюту", "Выбрать категорию", "Выбрать дату", "Сумма в рублях", "Добавить фото чека", "Способ оплаты", "Заметки"]
    
    var categories = ["Авиабилеты",
                      "Билеты на поезд",
                      "Проживание",
                      "Такси",
                      "Страхование",
                      "Вакцинация",
                      "Анализ на Covid-19",
                      "Другое"]
    
    let currencyNames = ["RUB", "AUD", "AZN", "GBP", "AMD", "BYN", "BGN", "BRL",
                         "HUF", "HKD", "DKK", "USD", "EUR", "INR", "KZT", "CAD",
                         "KGS", "CNY", "MDL", "NOK", "PLN", "RON", "XDR", "SGD",
                         "TJS", "TRY", "UZS", "TMT", "UAH", "CZK", "SEK", "CHF",
                         "ZAR", "KRW", "JPY"]
 
    let currencyRussianNames = [
        "Российский рубль", "Австралийский доллар", "Азербайджанский манат",
        "Фунт стерлингов Соединенного Королевства", "Армянских драмов",
        "Белорусский рубль", "Болгарский лев", "Бразильский реал",
        "Венгерских форинтов", "Гонконгских долларов", "Датская крона",
        "Доллар США", "Евро", "Индийских рупий", "Казахстанских тенге",
        "Канадский доллар", "Киргизских сомов", "Китайский юань",
        "Молдавскиз леев", "Норвежских крон", "Польский злотый", "Румынский лей",
        "СДР(специальные права заимствования)", "Сингапурский доллар",
        "Таджикских сомони", "Турецких лир", "Узбекских сумов",
        "Новый туркменский манат", "Украинских гривен", "Чешских крон",
        "Шведских крон", "Швейцарский франк", "Южноафриканских рэндов",
        "Вон Республики Корея", "Японских иен"
      ]
    
    let countries = [
        Country(name: "Andorra", code: "AD"),
        Country(name: "United Arab Emirates", code: "AE"),
        Country(name: "Afghanistan", code: "AF"),
        Country(name: "Antigua and Barbuda", code: "AG"),
        Country(name: "Anguilla", code: "AI"),
        Country(name: "Albania", code: "AL"),
        Country(name: "Armenia", code: "AM"),
        Country(name: "Netherlands Antilles", code: "AN"),
        Country(name: "Angola", code: "AO"),
        Country(name: "Antarctica", code: "AQ"),
        Country(name: "Argentina", code: "AR"),
        Country(name: "American Samoa", code: "AS"),
        Country(name: "Austria", code: "AT"),
        Country(name: "Australia", code: "AU"),
        Country(name: "Aruba", code: "AW"),
        Country(name: "Åland Islands", code: "AX"),
        Country(name: "Azerbaijan", code: "AZ"),
        Country(name: "Bosnia and Herzegovina", code: "BA"),
        Country(name: "Barbados", code: "BB"),
        Country(name: "Bangladesh", code: "BD"),
        Country(name: "Belgium", code: "BE"),
        Country(name: "Burkina Faso", code: "BF"),
        Country(name: "Bulgaria", code: "BG"),
        Country(name: "Bahrain", code: "BH"),
        Country(name: "Burundi", code: "BI"),
        Country(name: "Benin", code: "BJ"),
        Country(name: "Saint Barthélemy", code: "BL"),
        Country(name: "Bermuda", code: "BM"),
        Country(name: "Brunei Darussalam", code: "BN"),
        Country(name: "Bolivia", code: "BO"),
        Country(name: "Bonaire, Sint Eustatius and Saba", code: "BQ"),
        Country(name: "Brazil", code: "BR"),
        Country(name: "Bahamas", code: "BS"),
        Country(name: "Bhutan", code: "BT"),
        Country(name: "Bouvet Island", code: "BV"),
        Country(name: "Botswana", code: "BW"),
        Country(name: "Belarus", code: "BY"),
        Country(name: "Belize", code: "BZ"),
        Country(name: "Canada", code: "CA"),
        Country(name: "Cocos (Keeling) Islands", code: "CC"),
        Country(name: "Congo", code: "CD"),
        Country(name: "Central African Republic", code: "CF"),
        Country(name: "Switzerland", code: "CH"),
        Country(name: "Cook Islands", code: "CK"),
        Country(name: "Chile", code: "CL"),
        Country(name: "Cameroon", code: "CM"),
        Country(name: "China", code: "CN"),
        Country(name: "Colombia", code: "CO"),
        Country(name: "Costa Rica", code: "CR"),
        Country(name: "Cuba", code: "CU"),
        Country(name: "Cape Verde", code: "CV"),
        Country(name: "Curaçao", code: "CW"),
        Country(name: "Christmas Island", code: "CX"),
        Country(name: "Cyprus", code: "CY"),
        Country(name: "Czech Republic", code: "CZ"),
        Country(name: "Germany", code: "DE"),
        Country(name: "Denmark", code: "DK"),
        Country(name: "Dominican Republic", code: "DO"),
        Country(name: "Algeria", code: "DZ"),
        Country(name: "Ecuador", code: "EC"),
        Country(name: "Estonia", code: "EE"),
        Country(name: "Egypt", code: "EG"),
        Country(name: "Western Sahara", code: "EH"),
        Country(name: "Spain", code: "ES"),
        Country(name: "Ethiopia", code: "ET"),
        Country(name: "Finland", code: "FI"),
        Country(name: "Fiji", code: "FJ"),
        Country(name: "Falkland Islands (Malvinas)", code: "FK"),
        Country(name: "France", code: "FR"),
        Country(name: "Gabon", code: "GA"),
        Country(name: "United Kingdom", code: "GB"),
        Country(name: "Grenada", code: "GD"),
        Country(name: "Georgia", code: "GE"),
        Country(name: "Ghana", code: "GH"),
        Country(name: "Gibraltar", code: "GI"),
        Country(name: "Greenland", code: "GL"),
        Country(name: "Gambia", code: "GM"),
        Country(name: "Guinea", code: "GN"),
        Country(name: "Equatorial Guinea", code: "GQ"),
        Country(name: "Greece", code: "GR"),
        Country(name: "Guatemala", code: "GT"),
        Country(name: "Guam", code: "GU"),
        Country(name: "Hong Kong", code: "HK"),
        Country(name: "Honduras", code: "HN"),
        Country(name: "Croatia", code: "HR"),
        Country(name: "Haiti", code: "HT"),
        Country(name: "Jamaica", code: "JM"),
        Country(name: "Italy", code: "IT"),
        Country(name: "Iceland", code: "IS"),
        Country(name: "Iran, Islamic Republic", code: "IR"),
        Country(name: "Iraq", code: "IQ"),
        Country(name: "India", code: "IN"),
        Country(name: "Israel", code: "IL"),
        Country(name: "Ireland", code: "IE"),
        Country(name: "Indonesia", code: "ID"),
        Country(name: "Hungary", code: "HU"),
        Country(name: "Monaco", code: "MC"),
        Country(name: "Morocco", code: "MA"),
        Country(name: "Latvia", code: "LV"),
        Country(name: "Luxembourg", code: "LU"),
        Country(name: "Lithuania", code: "LT"),
        Country(name: "Liberia", code: "LR"),
        Country(name: "Sri Lanka", code: "LK"),
        Country(name: "Liechtenstein", code: "LI"),
        Country(name: "Kazakhstan", code: "KZ"),
        Country(name: "Cayman Islands", code: "KY"),
        Country(name: "Kuwait", code: "KW"),
        Country(name: "Korea", code: "KR"),
        Country(name: "Korea, Democratic People's Republic", code: "KP"),
        Country(name: "Cambodia", code: "KH"),
        Country(name: "Kyrgyzstan", code: "KG"),
        Country(name: "Kenya", code: "KE"),
        Country(name: "Japan", code: "JP"),
        Country(name: "Moldova", code: "MD"),
        Country(name: "Montenegro", code: "ME"),
        Country(name: "Madagascar", code: "MG"),
        Country(name: "Macedonia", code: "MK"),
        Country(name: "Mali", code: "ML"),
        Country(name: "Myanmar", code: "MM"),
        Country(name: "Mongolia", code: "MN"),
        Country(name: "Macao", code: "MO"),
        Country(name: "Mauritania", code: "MR"),
        Country(name: "Malta", code: "MT"),
        Country(name: "Mauritius", code: "MU"),
        Country(name: "Maldives", code: "MV"),
        Country(name: "Mexico", code: "MX"),
        Country(name: "Malaysia", code: "MY"),
        Country(name: "Namibia", code: "NA"),
        Country(name: "Niger", code: "NE"),
        Country(name: "Nigeria", code: "NG"),
        Country(name: "Nicaragua", code: "NI"),
        Country(name: "Netherlands", code: "NL"),
        Country(name: "Norway", code: "NO"),
        Country(name: "Nepal", code: "NP"),
        Country(name: "New Zealand", code: "NZ"),
        Country(name: "Oman", code: "OM"),
        Country(name: "Panama", code: "PA"),
        Country(name: "Peru", code: "PE"),
        Country(name: "Philippines", code: "PH"),
        Country(name: "Pakistan", code: "PK"),
        Country(name: "Poland", code: "PL"),
        Country(name: "Puerto Rico", code: "PR"),
        Country(name: "Palestine", code: "PS"),
        Country(name: "Portugal", code: "PT"),
        Country(name: "Qatar", code: "QA"),
        Country(name: "Romania", code: "RO"),
        Country(name: "Serbia", code: "RS"),
        Country(name: "Russian Federation", code: "RU"),
        Country(name: "Rwanda", code: "RW"),
        Country(name: "Saudi Arabia", code: "SA"),
        Country(name: "Seychelles", code: "SC"),
        Country(name: "Sudan", code: "SD"),
        Country(name: "Sweden", code: "SE"),
        Country(name: "Singapore", code: "SG"),
        Country(name: "Slovenia", code: "SI"),
        Country(name: "Slovakia", code: "SK"),
        Country(name: "Sierra Leone", code: "SL"),
        Country(name: "San Marino", code: "SM"),
        Country(name: "Senegal", code: "SN"),
        Country(name: "Somalia", code: "SO"),
        Country(name: "Suriname", code: "SR"),
        Country(name: "South Sudan", code: "SS"),
        Country(name: "Syrian Arab Republic", code: "SY"),
        Country(name: "Swaziland", code: "SZ"),
        Country(name: "Thailand", code: "TH"),
        Country(name: "Tajikistan", code: "TJ"),
        Country(name: "Turkmenistan", code: "TM"),
        Country(name: "Tunisia", code: "TN"),
        Country(name: "Turkey", code: "TR"),
        Country(name: "Taiwan", code: "TW"),
        Country(name: "Tanzania", code: "TZ"),
        Country(name: "Ukraine", code: "UA"),
        Country(name: "Uganda", code: "UG"),
        Country(name: "United States", code: "US"),
        Country(name: "Uruguay", code: "UY"),
        Country(name: "Uzbekistan", code: "UZ"),
        Country(name: "Venezuela", code: "VE"),
        Country(name: "Virgin Islands", code: "VG"),
        Country(name: "Vietnam", code: "VN"),
        Country(name: "Samoa", code: "WS"),
        Country(name: "Yemen", code: "YE"),
        Country(name: "South Africa", code: "ZA"),
        Country(name: "Zambia", code: "ZM"),
        Country(name: "Zimbabwe", code: "ZW")
    ]
    
    private init() {}
}
